# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74b928e422cfca3b834ade8a6ccea5b5854896a1add8346b6777bda091e6f8ce9fdc5ad10a39ed539a73356bcea2582fd322cdff5bd734a16dc821967218046f

test:
  secret_key_base: 78a935ac625bcbd54f3fa9e5eff915c82bb869c8145070c13eabdd97b0081a30a77aaa4a6c54cfde9aaa52bec950846be66f4d883c100c21ac800807b231a883

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
